### ISSUE TITLE
Plugin not working with SW 5.5.8

### ISSUE THREAD

**Issue by buddhaCode** [FriendsOfShopware/FroshExtendedPluginManager#1]
Hi Friends,
I just updated SW from 5.4.7 to 5.5.8 and the beautiful button is gone :( Any ideas? I can't see any errors in log file or javascript console.
Best,
buddha

**Comment by tinect** [comment]
hey @buddhaCode 
Just tested in 5.5.8 and everything looks good on my side.
Could you please check with fresh cache - particularly browsercache?

**Comment by buddhaCode** [comment]
Thanks. Yeah don't know what happend. It's working now. I had your old plugin with the tinect prefix installed. I now switched to the Frosh version. THX.
